# Generated by Django 4.2.4 on 2023-10-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, default='For Sale', help_text='For Rent or For sale', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
